theme: minima

markdown: kramdown
highlighter: rouge
permalink: pretty
gems: [jekyll-paginate]
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  input: GFM

# HTML Compression
compress_html:
  clippings               : all
  endings                 : all
  comments                : ["<!-- ", " -->"]
  blanklines              : true
  profile                 : false
  ignore:
  envs                    : [local]